### ISSUE TITLE
Spinbox part of the gui expands with larger window instead of graphs

### ISSUE THREAD

**Issue by mheidebr** [mheidebr/Electric-Car-Racing#49]
When displaying multiple charts it would be nice to be able to make the window size larger so we can see the data in more detail. When the window is made larger the left section (spin boxes and controls) of the gui expands to fill the space instead of the right side (charts). It would be nice to have the controls stay a constant width and the charts take up the rest of the available space in the window

**Comment by rdriven** [comment]
This can be (and is being) addressed in branch task/lock-user-control-size by "fixing" the user control width so that the contained controls won't stretch (remain the same size) when the user drags the app window to a larger size. Similarly the controls won't shrink in size if the app window is reduced in size.
